### ISSUE TITLE
Make acceptance tests run on Chrome driver

### ISSUE THREAD

**Issue by cosmingrz** [SpamExperts/plesk-linux-addon#6]
Modify tests in order to run on FirefoxDriver and ChromeDriver. In order to achieve that you will need to use CSS Locators and XPATHs with [Locator::combine](http://codeception.com/docs/reference/Locator#combine) function. Also repair tests if they are outdated.

**Comment by donici** [comment]
https://github.com/SpamExperts/plesk-linux-addon/commit/551f7b33ea892f6eac6c937e34d2b491879276e2 should also be covered with an automated test.
